name: Build EGL3

on: [push]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        include:
          - os: windows-2019
            name: Windows
            triplet: x64-windows
            configuration: x64-Release

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Get CMake
      uses: lukka/get-cmake@latest

    - name: Restore artifacts, or run vcpkg, build and cache artifacts
      uses: lukka/run-vcpkg@main
      id: runvcpkg
      with:
        vcpkgArguments: 'expat cpr mbedtls ixwebsocket rapidjson gtkmm'
        vcpkgTriplet: '${{ matrix.triplet }}'
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'

    - name: Run CMake
      uses: lukka/run-cmake@main
      with:
        cmakeListsOrSettingsJson: CMakeSettingsJson
        cmakeSettingsJsonPath: '${{ github.workspace }}/CMakeSettings.json'
        useVcpkgToolchainFile: true
        configurationRegexFilter: '${{ matrix.configuration }}'
    
    - name: Zip Archive
      run: |
        cd "${{ github.workspace }}"
        7z a archive.zip "C:\Program Files (x86)\EGL3\*" -r
        7z a archive.zip "extras\share" -r

    - name: Upload Archive
      uses: actions/upload-artifact@v2
      with:
        name: 'archive.zip'
        path: '${{ github.workspace }}\archive.zip'